
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simple_trello_db
    username: postgres
    password: 1113
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  banner:
    image:
      location: classpath:banner.txt
server:
  port: 9090